# Generated by Django 3.2.9 on 2021-12-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='livros',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
