# Generated by Django 3.2.9 on 2021-12-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
